### ISSUE TITLE
Playerhook issues

### ISSUE THREAD

**Issue by Darkfire1713** [Xandaros/evolve#132] opened 2015-04-07 00:19 UTC
Couldn't include file '..\..\includes\ev_von\von.lua' (File not found) (@addons/evolve-master/lua/autorun/server/ev_autorun.lua (line 17))

[ERROR] addons/evolve-master/lua/ev_framework.lua:420: attempt to index field 'von' (a nil value)
  1. LoadPlayerInfo - addons/evolve-master/lua/ev_framework.lua:420
   2. unknown - addons/evolve-master/lua/ev_framework.lua:425
    3. include - [C]:-1
     4. unknown - addons/evolve-master/lua/autorun/server/ev_autorun.lua:21

=====================================================
 Evolve 1.0 by Overv succesfully started serverside.
=====================================================

[EV] Hook 'Initialize' in plugin 'Restriction' failed with error:

[ERROR] addons/evolve-master/lua/ev_framework.lua:116: attempt to call method 'Log' (a nil value)
  1. Notify - addons/evolve-master/lua/ev_framework.lua:116
   2. unknown - addons/evolve-master/lua/ev_framework.lua:287

[EV] Hook 'InitPostEntity' in plugin 'Ban' failed with error:

[ERROR] addons/evolve-master/lua/ev_framework.lua:116: attempt to call method 'Log' (a nil value)
  1. Notify - addons/evolve-master/lua/ev_framework.lua:116
   2. unknown - addons/evolve-master/lua/ev_framework.lua:287

[EV] Hook 'PlayerSpawn' in plugin 'Player Info' failed with error:

[ERROR] addons/evolve-master/lua/ev_framework.lua:116: attempt to call method 'Log' (a nil value)
  1. Notify - addons/evolve-master/lua/ev_framework.lua:116
   2. unknown - addons/evolve-master/lua/ev_framework.lua:287

disabled all addons and it still happens. any ideas?

**Comment by Xandaros** [comment] 2015-04-07 05:11
Duplicate of #124 
You installed it incorrectly. There is a mini-tutorial in the last comment

**Closed by Xandaros** 2015-04-07 05:11 UTC
